version: '3.8'

services:
  ms_client:
    build:
      context: ./MS_CLIENT
    container_name: flask_api_client
    env_file:
      - .env
    ports:
      - "5001:5000"

  ms_commande:
    build:
      context: ./MS_COMMANDE
    container_name: flask_api_commande
    env_file:
      - .env
    ports:
      - "5002:5000"


  ms_produit:
    build:
      context: ./MS_PRODUIT
    container_name: flask_api_produit
    env_file:
      - .env
    ports:
      - "5003:5000"



