name: MS_PRODUIT CI Workflow

on:
  push:
    branches:
      - dev

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour les opérations Git qui nécessitent l'historique complet
          token: ${{ secrets.MY_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0' 

      - name: Install dependencies
        run: |
          cd MS_PRODUIT
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        id: pytest
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
        run: |
          cd MS_PRODUIT
          pytest

      - name: test_ok
        if: success()
        run: |
          git fetch
          git checkout main
          git merge --ff-only origin/dev
          git push origin main
          
      - name: test_ko
        if: failure()
        run: |
          unique_branch_suffix=$(date +%s)
          git checkout -b MS_PRODUIT/$unique_branch_suffix
          git push origin MS_PRODUIT/$unique_branch_suffix
          
          git checkout dev
          git reset --soft HEAD~1
          git push origin dev --force
